### ISSUE TITLE
SyntaxError trying to run wordprgui.py using Python 3.5.3

### ISSUE THREAD

**Issue by guest-porteus** [tututuana/WordProcessor#2]
`wordprgui.py` won't run for me on Python 3.5.3 due to the following Syntax Error -

`   File "wordprgui.py", line 38`
`      status_bar.config(text=f'{name} `                          `  ')`
........................................................^

`SyntaxError: invalid syntax`

**Comment by tnhnblgl** [comment]
i fixed it on [python3.5](https://github.com/tututuana/WordProcessor/tree/python3.5) branch.
You can clone this branch by typing `git clone -b python3.5 https://github.com/tututuana/WordProcessor.git`
